name: Build Android APK (Manual)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Chọn môi trường build'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  build_apk:
    name: Build APK (${{ github.event.inputs.environment || 'dev' }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: '.fvmrc'
          cache: true

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: |
          flutter build apk --debug --dart-define-from-file=config/env.example.json

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: giatocviet-${{ github.event.inputs.environment || 'dev' }}-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 7
